#!/usr/bin/ruby
# ecoding:utf-8
require '~/.scripts/bibus_utils.rb'

username = 'linsj'
datafile = '.bibus/Data/Daily.db'

refdir = "#{Dir.home}/Documents/Reference/"
tmpfile = "#{Dir.home}/Documents/tmp.bib"

filename = ARGV[0] || 'back_filename'
bibfile = ARGV[1] || tmpfile

bib = Bibus.new(username, datafile)
bib.addbib(filename, bibfile)
FileUtils.mv(bibfile, tmpfile) if bibfile != tmpfile
