#!/usr/bin/ruby
# ecoding:utf-8
require '~/.scripts/bibus_utils.rb'

username = 'linsj'
datafile = '.bibus/Data/Daily.db'

refdir = "#{Dir.home}/Documents/Reference/"
tmpfile = "#{Dir.home}/Documents/tmp.bib"

bibfile = ARGV[0] || tmpfile

bib = Bibus.new(username, datafile)
bib.modbib(bibfile)
FileUtils.mv(bibfile, tmpfile) if bibfile != tmpfile
