#!/usr/bin/ruby
# ecoding:utf-8
require '~/.scripts/bibus_utils.rb'

username = 'linsj'
datafile = '.bibus/Data/Daily.db'
user_s = 'linsj'

hdir = "/home/#{user_s}/"
refdir = "#{hdir}Documents/Reference/"
tmpfile = "#{hdir}Documents/tmp.bib"

filename = ARGV[0] || 'back_filename'
bibfile = ARGV[1] || tmpfile

bib = Bibus.new(username, user_s, datafile)
bib.addbib(filename, bibfile)
FileUtils.mv(bibfile, tmpfile) if bibfile != tmpfile
