#!/usr/bin/ruby
# ecoding:utf-8
require '/home/linsj/.scripts/bibus_utils.rb'

username = 'linsj'
datafile = '.bibus/Data/Daily.db'
user_s = 'linsj'

bib = Bibus.new(username, user_s, datafile)
bibkey = ARGV[0].chomp

bib.d_bib(bibkey)
