#!/usr/bin/ruby
# ecoding:utf-8
require '~/.scripts/bibus_utils.rb'

username = 'linsj'
datafile = '.bibus/Data/Daily.db'
user_s = 'linsj'

def getidenti
  puts "please input the identifier of the file you want to open:\n"
  $stdin.gets
end

bibkey = ARGV[0] || getidenti.chomp

hdir = "/home/#{user_s}/"
refdir = "#{hdir}Documents/Reference/"

bib = Bibus.new(username, user_s, datafile, refdir)
bib.opbib(bibkey)
