#!/usr/bin/ruby
# ecoding:utf-8
require '~/.scripts/bibus_utils.rb'

username = 'linsj'
datafile = '.bibus/Data/Daily.db'
user_s = 'linsj'

def getidenti(content)
  wthto = ->(cont) { cont == "keyname" ? ' to' : '' }
  puts "please input the #{content} you want to link#{wthto.call(content)}:\n" 
  $stdin.gets
end

(adorde, keyname, bibkey) = ARGV
keyname ||= getidenti('keyname').chomp
bibkey ||= getidenti('identifier').chomp

hdir = "/home/#{user_s}/"
refdir = "#{hdir}Documents/Reference/"

bib = Bibus.new(username, user_s, datafile, refdir)
adorde == 'add' ? bib.links(keyname, bibkey) : bib.delinks(keyname, bibkey)
