#!/usr/bin/ruby
def multi_col colnum
  list=[]
  wordlen=0
  $stdin.each_line {|line|
    line.chomp!
    line.strip!
    list.push line
    wordlen=line.size if line.size>wordlen
  }
  maxline=list.size.fdiv colnum.to_i
  maxline=maxline.ceil
  table=[]
  (0..(list.size-1)).each {|index|
    l_ind=index%maxline
    table[l_ind]=list[index].ljust wordlen if(index/maxline==0)
    table[l_ind]+="\t#{list[index].ljust wordlen}" if(index/maxline>0)
  }
  puts table
end

colnum=ARGV[0]
multi_col colnum
