#!/usr/bin/ruby
# encoding: utf-8

require '~/.scripts/bibus_utils.rb'

username = 'linsj'
datafile = '.bibus/Data/Daily.db'
user_s = 'linsj'

bib = BibusSearch.new(username, user_s, datafile)
bib.search(ARGV)
