#!/usr/bin/env ruby
# encoding: utf-8

load File.expand_path('~/.bibcmdrc')
require BIBUTILS
require CMDUTILS
require 'curses'
include Curses

bib = Bibus.new(USER_NAME, DATA_FILE, REF_DIR, ANCESTOR)

begin
init_screen
cbreak
noecho
curs_set(0)
start_color
use_default_colors
colorinit

cmd = CmdBib.new(lines, cols, bib)
cmd.deal

ensure
close_screen
end
