#!/usr/local/bin/ruby
#!/home/linsj/bin/ruby
# encoding: utf-8

require '~/ruby_cpp/Chisq/Chisq'
require '~/.scripts/stringtof.rb'

x, num = ARGV[0].dup.e_to_f, ARGV[1].dup.e_to_f.to_i

p x, num
puts ARGV[2] == 'r' ? Chisq::chi2(alpha = x, num) : alpha = Chisq::alpha(x, num)
puts "#{format("%.3g", Chisq::getnsig(alpha))} sigma"
