#!/usr/bin/env ruby
# encoding: utf-8

require 'fileutils'

def clean(file)
  puts("Cleaning:") unless $notfirst
  $notfirst ||= true

  puts("  #{file}")
  FileUtils.rm(file)
end

filename = ARGV[0] || '.'

raise 'Please specify an avialable path name' unless File.directory?(filename)

Dir.glob("#{filename}/*").select { |f| File.size(f) == 0 }
  .each { |f| clean(f) }
