#!/bin/bash
git config --global push.default simple
git config user.name 'linsj'
git config user.email 'lin.sujie1234@gmail.com'
git config core.editor vim
git config core.paper "less -N"
git config color.diff true
git config alias.co checkout
