#!/usr/bin/env ruby
require 'pathname'

def gvopen(path)
  path = Pathname.new(path).expand_path
  reg = Regexp.new(path.basename.to_s)

  path.dirname.each_child.select { |x| reg =~ x.to_s }
  .each { |x| system("gv #{x} &") }
end

ARGV.each { |x| gvopen(x) }
