#!/home/linsj/bin/ruby

USER = 'linsj'
DIRS = { local: ['~/Documents/Reference',\
           '~/Documents/TeXfile', '~/.bibus'], \
         sv: ['~/recdat', '~/MCGAL/GALDEF'] }
CLS = { sv1: :sv, sv2: :sv, sv3: :sv, sv4: :sv, local: :local, nil => :local }
OPTIONS = '-avzru --exclude="*.swp"'

def parent(dir)
  dir.sub(/\/[0-9a-zA-Z._-]+$/, '')
end

def checkname(ip)
  /Host (?<name>\w+)/ =~ File.new(File.expand_path('~/.ssh/config')).read
     .split("\n\n").select { |item| /#{ip}/ =~ item }[0]
  name
end

def act(command)
  puts command
  system(command)
end

def sync(server, dirs)
  dirs.each { |d| act("rsync #{OPTIONS} #{server}:#{d} #{parent(d)}") }
  dirs.each { |d| act("rsync #{OPTIONS} #{d} #{server}:#{parent(d)}") }
end

def getip(line)
  /\s+inet (?:addr:)?(?<ip>(?:[0-9]{1,3}\.{1}){3}[0-9]{1,3})/ =~ line
  ip
end

ips = `ifconfig`.each_line.map { |l| getip(l) }.compact
local = (ips.map { |i| checkname(i) }.compact[0] || "local").to_sym
target = ARGV[0].to_sym

sync(target, DIRS[CLS[local]] & DIRS[CLS[target]])
