#!/bin/ruby
# encoding:utf-8

def dealline(line)
  dealsap = ->(str) { str =~ /^\s*\++\s*$/ ? "\r\n#{str}\r\n" : str }
  /(?<lin>.+)\r\n/ =~ line ? dealsap.call(lin + ' ') : "\r\n\r\n"
end

filename = ARGV[0] || exit

file = File.new(filename).map { |line| dealline(line) }.join('')
         .gsub(/[ ]+/, ' ').gsub(" \r\n", "\r\n")

File.new(filename, 'w').puts(file)
