#!/usr/bin/ruby
# encoding: utf-8

require '~/.scripts/bibus_utils.rb'
require '~/.scripts/cmdbib_utils.rb'

username = 'linsj'
datafile = '.bibus/Data/Daily.db'
user_s = 'linsj'

bib = BibusSearch.new(username, user_s, datafile)
(ident, author, title, notes) = bib.getnote(ARGV[0])
head = [title, author, ident]

init_screen
start_color
use_default_colors
colorinit

noecho
curs_set(0)

pad = NoteItf.new(notes, head, [lines, cols], cols, 1)
pad.deal
bib.storenote(ident, pad.note.notes)

close_screen
