#!/usr/bin/ruby
# ecoding:utf-8
require '~/.scripts/bibus_utils.rb'

username = 'linsj'
datafile = '.bibus/Data/Daily.db'

def getidenti
  puts "please input the identifier of the file you want to open:\n"
  $stdin.gets
end

bibkey = ARGV[0] || getidenti.chomp

refdir = "#{Dir.home}/Documents/Reference/"

bib = Bibus.new(username, datafile, refdir)
bib.opbib(bibkey)
