#!/bin/env ruby
# encoding:utf-8

require 'escort'
require 'rainbow/ext/string'

class String
  def begin_with?(str)
    strip.start_with?(str)
  end
end

# The class to read and write tex file in a standard format
# All the content is stored in a array of hashs, each hash is a single
# sentence with its status: [txt|annotate|gap|environment].
class TeXFile
  attr_reader :content

  def initialize
    @content = []
    @status = []
    @inbrace = nil
  end

  def readline(str)
    dealstatus(str)
    return if @status.empty?

    return addgap if str =~ /^$/

    @annotates ||= []
    sentence, annotate = sentence_splitor(str)

    if @status[-1] == :command_begin
      @status[-1] = :command
      changeline
    end

    if @status[-1] == :txt || @status[-1] == :command
      ([''] + sentence.split(/[ ]/) + ['']).each_cons(3) { |lw, w, nw| word_recording(lw, w, nw) }
    else
      add_evironment_line(sentence)
    end

    @annotates << annotate unless annotate.empty?
  end

  def add_evironment_line(str)
    return if str.empty?
    changeline
    @content[-1][0] << str.chomp
  end

  def sentence_splitor(str)
    %r{(?<sentence>.*?)(?<annotate>(?<!\\)%.*)} =~ str
    annotate ? [sentence, annotate] : [str, '']
  end

  def word_recording(lw, w, nw)
    changeline if @content.empty? || @status[-1] != @content[-1][1]
    changeline if @tochange
    addword(w)
    tochangeline if eol?(lw, w, nw)
  end

  def addword(w)
    return if w.empty? || !@content[-1] || @content[-1][1] == :gap

    space = @content[-1][0].empty? ? '' : ' '
    @content[-1][0] << (space + w.strip)
  end

  def tochangeline
    @tochange = true
  end

  def changeline
    @annotates.each { |a| @content.insert(-1, [a, :annotate, :annotate]) }

    @annotates.clear
    @content << ['', @status[-1], @status.clone]
    @tochange = false
  end

  NOT_END = %w(i.e. fig. Fig. pic. Pic. Tab. tab. Table. eq. Eq. Ref. e.g. Sec. Section. No. C.L.)
  N_NOT_END = ['table. \\', 'section. \\', 'P. R.']
  L_NOT_END = ['et al.', 'P. R.']
  def eol?(lw, w, nw)
    not_end = NOT_END.include?(w.chomp) ||
      N_NOT_END.reduce(false) { |a, e| a || "#{w.chomp} #{nw.chomp}".start_with?(e) } ||
      L_NOT_END.reduce(false) { |a, e| a || ("#{lw.chomp} #{w.chomp}" == e) }

    return false if not_end
    w.chomp.end_with?('.')
  end

  def addgap
    return if @content[-1][1] == :gap
    changeline
    @content[-1] = ['', :gap, :gap]
  end

  def print(file, type, debug = false)
    return puts(@content.map { |c, s, s1| "#{c.chomp} #{s1.to_s.color(:white)}" }) if debug
    outfile = File.new(file, 'w')
    outfile.puts to_s(type.to_sym)
    outfile.close
  end

  def to_s(type = :sentence)
    return sentence_to_s if type == :sentence

    lines = ['']
    last_s = nil
    @content.each do |c, s|
      if ![:txt, :command].include?(s)
        lines[-1].empty? ? lines[-1] << c : lines << c
        lines << ''
        next
      end

      lines << '' if last_s != s && !lines[-1].empty?
      append_line(lines, c)

      last_s = s
    end

    lines
  end

  def sentence_to_s
    format_result = @content.each_with_object([]) do |l, a|
      a[-1][0].chomp! if a[-1] && a[-1][2] == [:environment] && l[1] == :annotate
      a << [l[0].chomp + "\n", l[1], l[2]]
    end
    format_result.transpose[0].join('')
  end

  WIDTH = 80
  def append_line(arr, line)
    words = arr[-1].split(' ') + line.split(' ')

    line.split(' ').each do |w|
      if arr[-1].size + w.size <= WIDTH
        arr[-1] << " #{w}"
      else
        arr << " #{w}"
      end
    end
  end

  def count_brace(str)
    @inbrace += str.count('{')
    @inbrace -= str.count('}')
  end

  CMDLIST = %w(caption title author abstract affiliation)
  def dealstatus(str)
    @status.pop if @status[-1].to_s =~ /\w+_end/
    @status.pop if @status[-1] == :command && @inbrace == 0

    case true
    when str.begin_with?('\documentclass') then @status << :environment
    when str.begin_with?('\begin{document}')
      @status.pop
      @status << :txt
    when !(str =~ %r[(\\end{(abstract|acknowledgments)|\\begin{(abstract|acknowledgments))]).nil?
      @status << :environment_end
    when str.begin_with?('\end')
      @status[-1] = "#{@status[-1]}_end".to_sym
    when str.begin_with?('\begin{')
      @status << :environment
    when !(str =~ %r[^\s*\\(caption|title|author|abstract|affiliation|section|subsection){]).nil? #CMDLIST.reduce(false) { |a, e| a || str.begin_with?("\\#{e}{") }
      @status << :command_begin
      @inbrace = 0
      count_brace(str)
    when @status[-1] == :command && @inbrace > 0
      count_brace(str)
    end
  end
end

class DealTex < ::Escort::ActionCommand::Base
  def execute
    raise 'No input file found' unless command_options[:infile]
    command_options[:outfile] ||= command_options[:infile]

    tex = TeXFile.new
    infile = File.new(command_options[:infile])
    infile.each.to_a.each { |l| tex.readline(l) }
    infile.close

    tex.print(command_options[:outfile], command_options[:type], command_options[:debug])
  end
end

Escort::App.create do |app|
  app.summary 'This script is used to convert the texformat to two kinds of standard form'

  app.options do |opts|
    opts.opt :infile, 'Input file', short: '-i', long: '--in-file', type: :string
    opts.opt :outfile, 'Output file it would be the same as Input file by default',
      short: '-o', long: '--out-file', type: :string
    opts.opt :type, 'The type of output file', short: '-t', long: '--type',
      type: :string, default: 'sentence'
    opts.opt :debug, 'Show debug info or not', short: '-d', long: '--debug',
      type: :bool, default: false

    opts.validate(:type, 'must be "sentence" or "paragraph"') { |o| %w(sentence paragraph).include?(o) }
  end

  app.action do |options, arguments|
    DealTex.new(options, arguments).execute
  end
end
